// UI Reducer action types

export const TOGGLE_NAV_DRAWER_OPEN = 'TOGGLE_NAV_DRAWER_OPEN';
export const TOGGLE_FILTER_DRAWER_OPEN = 'TOGGLE_FILTER_DRAWER_OPEN';

export const ADD_NEW_TUTOR = 'ADD_NEW_TUTOR';
export const CHANGE_CURRENT_TUTOR = 'CHANGE_CURRENT_TUTOR';